# Generated by Django 4.2.3 on 2023-08-02 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_remove_comment_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='name',
        ),
        migrations.AddField(
            model_name='comment',
            name='city_name',
            field=models.CharField(default='', max_length=80, verbose_name='City'),
        ),
    ]
