# Generated by Django 4.2.3 on 2023-08-03 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_remove_comment_name_comment_city_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='dish_id',
        ),
    ]
