# Generated by Django 4.2.3 on 2023-08-03 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_apidish_picture'),
        ('main_app', '0009_rename_post_comment_dish_id'),
    ]

    operations = [
    ]
