# Generated by Django 4.2.3 on 2023-08-03 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_merge_20230803_1718'),
        ('main_app', '0010_merge_20230803_1722'),
    ]

    operations = [
    ]
