# Generated by Django 4.2.3 on 2023-08-03 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_merge_20230803_2023'),
        ('main_app', '0012_comment_user_delete_userprofile'),
    ]

    operations = [
    ]
