# Generated by Django 4.2.3 on 2023-08-04 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_merge_20230803_1758'),
        ('main_app', '0013_merge_20230803_2215'),
        ('main_app', '0013_photo'),
    ]

    operations = [
    ]
